---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: pch-r
 spec:
   replicas: 2
   template:
     metadata:
       labels:
         app: web
     spec:
       containers:
         - name: rss-reader
           image: ankit1997/get-started:part2
           ports:
             - containerPort: 88
